In [1]:
import numpy as np

In [6]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

8

In [10]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
clice = arr[:3]
clice[:] = 99

In [14]:
arr

array([ 99,  99,  99, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
mat = np.array([[5,10,15], [20,25,30], [47,25,30]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [47, 25, 30]])

In [20]:
mat[0][2]

15

In [21]:
mat[0,2]

15

In [24]:
mat[1:,:2]

array([[20, 25],
       [47, 25]])

In [25]:
arr = np.arange(1,11)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])